import Nav from "@/components/Nav";
import Head from "next/head";
import Image from "next/image";
// import im from "../public/assets/crew/image-anousheh-ansari.png";

import { crew } from "../data/data.json";
import { useEffect, useState } from "react";

function CrewPage() {
	const [crews, setCrews] = useState(crew);
	const [crewIndex, setIndex] = useState(0);
	return (
		<>
			<Head>
				<title>Space Tour</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			<main className="h-screen overflow-hidden w-full bg-crewBgMobile bg-no-repeat bg-cover md:bg-crewBgTablet lg:bg-crewBgDesktop relative">
				<Nav />
				<section className="flex items-center gap-6 lg:items-end lg:justify-between flex-col md:gap-36 lg:flex-row h-full w-full pb-10 md:pb-24 lg:pb-16 lg:px-28 ">
					<p className="uppercase font-bold text-white text-[16px] lg:text-[28px] tracking-[2.7px] lg:tracking-[4.72px]">
						<span className="text-white/50 mr-2">02</span>
						meet your crew
					</p>
					<section className="px-[1.5rem] flex flex-col items-center gap-8">
						<div className="w-[327px] h-[223px] relative">
							<Image
								src={crews[crewIndex].images.png}
								alt=""
								fill
								className="w- h- object-contain"
							/>
						</div>
						<hr className="h-[1px] w-full bg-lightBlue/30 border-none" />
						<div className="flex flex-col items-center gap-5">
							<div className="dots flex gap-3">
								{crews.map((element, index) => (
									<div
										key={index}
										onClick={() => setIndex(index)}
										className="h-3 w-3 bg-white/20 rounded-full cursor-pointer hover:bg-white"
									></div>
								))}
							</div>
							<div className="details flex flex-col items-center">
								<h6 className="uppercase text-white/50 text-center">
									{crews[crewIndex].role}
								</h6>
								<h3 className="uppercase text-center text-[24px] text-white mb-2">
									{crews[crewIndex].name}
								</h3>
								<p className="text-lightBlue text-center text-[15px] leading-[25px] w-[85%]">
									{crews[crewIndex].bio}
								</p>
							</div>
						</div>
					</section>
				</section>
			</main>
		</>
	);
}

export default CrewPage;
