import Nav from "@/components/Nav";
import Head from "next/head";
import Image from "next/image";

import { destinations } from "../data/data.json";
import { useEffect, useState } from "react";

function destination() {
  const [destination, setDestination] = useState(destinations);
  const [planetIndex, setIndex] = useState(0);

  return (
    <>
      <Head>
        <title>Space Tour</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />

        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed&family=Bellefair&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="h-screen overflow-hidden w-full bg-destBgMobile bg-no-repeat bg-cover md:bg-destBgTablet lg:bg-destBgDesktop relative">
        <Nav />
        <section className="flex items-center justify-center gap-20 lg:items-end lg:justify-between flex-col md:gap-36 lg:flex-row h-full w-full pb-10 md:pb-24 lg:pb-16 lg:px-28 ">
          <p className="uppercase font-bold text-white text-[16px] lg:text-[28px] tracking-[2.7px] lg:tracking-[4.72px]">
            <span className="text-white/50 mr-2">01</span>
            pick your destination
          </p>
          <section className="px-[1.5rem] flex flex-col items-center gap-10">
            <div className="w-[170px] h-[170px] relative">
              <Image
                src={destination[planetIndex].images.png}
                alt=""
                fill
                // width={170}
                // height={170}
                className="animate-spin-slow"
              />
            </div>
            <div>
              <div className="flex items-center justify-center gap-7 h-6 mb-2">
                {destination.map((i, index) => (
                  <p
                    key={i.name}
                    className="dest-nav relative h-full text-white uppercase text-[14px] tracking-[2.36px]"
                    onClick={() => setIndex(index)}
                  >
                    {i.name}
                  </p>
                ))}
              </div>
              <div>
                <h1 className="text-[56px] uppercase text-white text-center">
                  {destination[planetIndex].name}
                </h1>
                <p className="text-[15px] mx-auto w-[88%] leading-[25px] text-center text-lightBlue">
                  {destination[planetIndex].description}
                </p>
                <hr className="h-[1px] bg-lightBlue/30 border-none my-8" />
                <div className="flex flex-col gap-5">
                  <div className="text-center">
                    <p
                      className="text-lightBlue text-[14px] tracking-[2.36px] mb-2 uppercase
                "
                    >
                      avg. distance
                    </p>
                    <h3 className="text-[28px] text-white uppercase">
                      {destination[planetIndex].distance}
                    </h3>
                  </div>
                  <div className="text-center">
                    <p
                      className="text-lightBlue text-[14px] tracking-[2.36px] mb-2 uppercase
                "
                    >
                      est. travel time
                    </p>
                    <h3 className="text-[28px] text-white uppercase">
                      {destination[planetIndex].travel}
                    </h3>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </section>
      </main>
    </>
  );
}

export default destination;
