import Nav from "@/components/Nav";
import Head from "next/head";
import Image from "next/image";

import { destinations } from "../data/data.json";
import { useRef, useState } from "react";

function Destination() {
	const [destination, setDestination] = useState(destinations);
	const [planetIndex, setIndex] = useState(0);
	// const [sty, setSty] = useState();

	let initVal = useRef(null);
	// console.log(initVal.current.childNodes[0]);
	const handleDest = function (index) {
		setIndex(index);
	};
	// useEffect(() => {}, []);

	return (
		<>
			<Head>
				<title>Space Tour</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			<main className="h-screen overflow-hidden w-full bg-destBgMobile bg-no-repeat bg-cover md:bg-destBgTablet lg:bg-destBgDesktop relative flex flex-col gap-5">
				<Nav />
				<section className="flex items-center gap-10 flex-col h-full w-full pb-10 md:pb-24 lg:pb-16 lg:px-28 lg:py-0 lg:gap-6">
					<p className="uppercase font-bold text-white text-[1rem] lg:text-[1.5rem] tracking-[2.7px] md:mt-8 md:self-start lg:tracking-[4.72px] md:pl-8 md:text-[1.2rem] lg:w-full">
						<span className="text-white/50 mr-2">01</span>
						pick your destination
					</p>
					<section className="px-[1.5rem] flex flex-col items-center gap-10 lg:flex-row lg:justify-between">
						<div className="lg:w-[40%]  flex items-center justify-center">
							<div className="w-[170px] h-[170px] relative md:w-[300px] md:h-[300px] lg:w-[400px] lg:h-[400px]">
								<Image
									src={destination[planetIndex].images.png}
									alt=""
									fill
									// width={170}
									// height={170}
									className=" object-contain animate-spin-slow "
								/>
							</div>
						</div>
						<div className="lg:w-[40%]">
							<div
								className="flex items-center justify-center gap-7 h-6 mb-2 lg:justify-start"
								ref={initVal}
							>
								{destination.map((i, index) => (
									<p
										key={index}
										className="dest-nav relative h-full text-white uppercase text-[14px] tracking-[2.36px]"
										onClick={() => handleDest(index)}
									>
										{i.name}
									</p>
								))}
							</div>
							<div>
								<h1 className="text-[56px] lg:text-[5.5rem] uppercase text-white text-center lg:text-left">
									{destination[planetIndex].name}
								</h1>
								<p className="text-[15px] mx-auto w-[88%] md:w-[60%] leading-[25px] text-center text-lightBlue lg:text-left lg:mx-0 lg:text-lg lg:pr-8">
									{destination[planetIndex].description}
								</p>
								<hr className="h-[1px] bg-lightBlue/30 border-none my-8" />
								<div className="flex flex-col gap-5  text-center lg:text-left md:flex-row md:gap-20 md:justify-center lg:gap-[unset] lg:justify-start">
									<div className="lg:mr-14">
										<p
											className="text-lightBlue text-[14px] tracking-[2.36px] mb-2 uppercase
                "
										>
											avg. distance
										</p>
										<h3 className="text-[28px] text-white uppercase">
											{destination[planetIndex].distance}
										</h3>
									</div>
									<div className="">
										<p
											className="text-lightBlue text-[14px] tracking-[2.36px] mb-2 uppercase
                "
										>
											est. travel time
										</p>
										<h3 className="text-[28px] text-white uppercase">
											{destination[planetIndex].travel}
										</h3>
									</div>
								</div>
							</div>
						</div>
					</section>
				</section>
			</main>
		</>
	);
}

export default Destination;
