import Head from "next/head";

import Nav from "@/component/Nav";

export default function Home() {
  return (
    <>
      <Head>
        <title>Space Tour</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        {/* <link rel="icon" href="/favicon.ico" />*/}
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow+Condensed&family=Bellefair&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="h-screen w-full bg-cover bg-no-repeat bg-hero md:bg-hero-md xl:bg-hero-lg bg-bottom relative">
        <Nav />
        <section className="flex items-center justify-end gap-8 lg:items-end lg:justify-between flex-col lg:flex-row h-full w-full pb-7 lg:px-32 lg:pb-10">
          <div className="text-white uppercase text-center lg:text-left w-full px-10 lg:px-0 lg:w-[400px]">
            <p className="text-[16px] lg:text-[28px] tracking-[4.72px]">
              so, you want to travel to
            </p>
            <h1 className="text-[80px]">space</h1>
            <p className=" text-[15px] lg:text-[18px]  leading-[25px] lg:leading-[32px]">
              Let’s face it; if you want to go to space, you might as well
              genuinely go to outer space and not hover kind of on the edge of
              it. Well sit back, and relax because we’ll give you a truly out of
              this world experience!
            </p>
          </div>
          <div className="bg-white w-[150px] h-[150px] rounded-full grid place-items-center md:w-[242px] md:h-[242px] lg:w-[274px] lg:h-[274px]">
            <h5 className="uppercase ">explore</h5>
          </div>
        </section>
      </main>
    </>
  );
}
