import Nav from "@/components/Nav";
import Head from "next/head";
import Image from "next/image";
import data from "../data/data.json";
import { useState } from "react";
function Technologies() {
	const { destination, crew, technology } = { ...data };
	const [tech, setTech] = useState(technology);
	const [index, setIndex] = useState(0);
	return (
		<>
			<Head>
				<title>Space Tour</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			<main className="relative bg-technologyBgMobile bg-no-repeat h-screen w-full bg-cover md:bg-technologyBgTablet lg:bg-technologyBgDesktop overflow-hidden">
				<Nav />
				<section
					className="flex flex-col items-center gap-6 lg:items-end lg:justify-between md:gap-36 lg:flex-row h-full w-full pb-10 md:pb-24 lg:pb-16 lg:px-28 
        "
				>
					<p className="uppercase font-bold text-white text-[16px] lg:text-[28px] tracking-[2.7px] lg:tracking-[4.72px]">
						<span className="text-white/50 mr-2">03</span>
						space launch 101
					</p>
					<div className="relative w-full h-[170px] mb-4">
						<Image
							src={tech[index].images.landscape}
							alt=""
							fill
							className=""
						/>
					</div>
					<div className="flex gap-4">
						{tech.map((element, index) => {
							return (
								<div
									key={index}
									onClick={() => setIndex(index)}
									className="grid place-items-center rounded-full w-[40px] h-[40px] bg-white text-2xl
            "
								>
									<h6>{index + 1}</h6>
								</div>
							);
						})}
					</div>
					<div>
						<div className="text-center mb-4">
							<p className="uppercase text-lightBlue tracking-[2.36px] mb-1">
								the technology...
							</p>
							<h5 className="uppercase text-white text-[24px]">
								{tech[index].name}
							</h5>
						</div>
						<p className="text-center text-lightBlue text-[15px] px-7 leading-[25px]">
							{tech[index].description}
						</p>
					</div>
				</section>
			</main>
		</>
	);
}

export default Technologies;
